/**
 * StudyOS - Exam Seed Data (v1.0.2 Matrix)
 *
 * Predefined exams covering Engineering, Medical, Government, Railways,
 * Banking, Civil Services, Defence, Management, Law, Graduate/GATE, School Boards & Overseas.
 */

const EXAM_SEEDS = [
  // ─── Engineering (National, State & Private Colleges) ──────────────────────────
  {
    name: 'JEE Main',
    slug: 'jee-main',
    category: 'engineering',
    description: 'Joint Entrance Examination Main — national-level entrance for NITs, IIITs, and CFTIs.',
    subjects: ['Physics', 'Chemistry', 'Mathematics'],
    duration: 180,
    totalMarks: 300,
    eligibility: 'Class 12 passed or appearing with Physics and Mathematics.',
    officialUrl: 'https://jeemain.nta.nic.in',
    icon: 'jee',
    sortOrder: 1,
  },
  {
    name: 'JEE Advanced',
    slug: 'jee-advanced',
    category: 'engineering',
    description: 'Joint Entrance Examination Advanced — entrance for premier IITs.',
    subjects: ['Physics', 'Chemistry', 'Mathematics'],
    duration: 180,
    totalMarks: 360,
    eligibility: 'Top 2,50,000 qualified candidates in JEE Main.',
    officialUrl: 'https://jeeadv.ac.in',
    icon: 'jee-adv',
    sortOrder: 2,
  },
  {
    name: 'BITSAT',
    slug: 'bitsat',
    category: 'engineering',
    description: 'BITS Admission Test for BITS Pilani, Goa, and Hyderabad campuses.',
    subjects: ['Physics', 'Chemistry', 'Mathematics', 'English Proficiency', 'Logical Reasoning'],
    duration: 180,
    totalMarks: 390,
    eligibility: 'Class 12 passed with 75% aggregate in PCM.',
    officialUrl: 'https://bitsadmission.com',
    icon: 'bitsat',
    sortOrder: 3,
  },
  {
    name: 'WBJEE',
    slug: 'wbjee',
    category: 'engineering',
    description: 'West Bengal Joint Entrance Examination for Jadavpur & West Bengal engineering colleges.',
    subjects: ['Mathematics', 'Physics', 'Chemistry'],
    duration: 240,
    totalMarks: 200,
    eligibility: 'Class 12 passed with Physics, Mathematics, and Chemistry/Bio.',
    officialUrl: 'https://wbjeeb.nic.in',
    icon: 'wbjee',
    sortOrder: 4,
  },
  {
    name: 'COMEDK UGET',
    slug: 'comedk-uget',
    category: 'engineering',
    description: 'Consortium of Medical, Engineering and Dental Colleges of Karnataka entrance test.',
    subjects: ['Physics', 'Chemistry', 'Mathematics'],
    duration: 180,
    totalMarks: 180,
    eligibility: 'Class 12 passed with 45% marks in PCM.',
    officialUrl: 'https://comedk.org',
    icon: 'comedk',
    sortOrder: 5,
  },
  {
    name: 'KCET',
    slug: 'kcet',
    category: 'engineering',
    description: 'Karnataka Common Entrance Test for state engineering and farm science colleges.',
    subjects: ['Physics', 'Chemistry', 'Mathematics', 'Biology'],
    duration: 240,
    totalMarks: 180,
    eligibility: 'Karnataka domicile Class 12 with PCM/PCB.',
    officialUrl: 'https://cetonline.karnataka.gov.in',
    icon: 'kcet',
    sortOrder: 6,
  },
  {
    name: 'MHT CET',
    slug: 'mht-cet',
    category: 'engineering',
    description: 'Maharashtra Common Entrance Test for state engineering and pharmacy institutes.',
    subjects: ['Physics', 'Chemistry', 'Mathematics'],
    duration: 180,
    totalMarks: 200,
    eligibility: 'Class 12 passed with Physics, Mathematics, and Chemistry.',
    officialUrl: 'https://cetcell.mahacet.org',
    icon: 'mht-cet',
    sortOrder: 7,
  },
  {
    name: 'VITEEE',
    slug: 'viteee',
    category: 'engineering',
    description: 'Vellore Institute of Technology Engineering Entrance Examination.',
    subjects: ['Physics', 'Chemistry', 'Mathematics', 'Aptitude', 'English'],
    duration: 150,
    totalMarks: 125,
    eligibility: 'Class 12 with 60% aggregate in PCM/PCB.',
    officialUrl: 'https://viteee.vit.ac.in',
    icon: 'viteee',
    sortOrder: 8,
  },
  {
    name: 'SRMJEEE',
    slug: 'srmjeee',
    category: 'engineering',
    description: 'SRM Joint Engineering Entrance Examination for SRM IST campuses.',
    subjects: ['Physics', 'Chemistry', 'Mathematics', 'Aptitude', 'English'],
    duration: 150,
    totalMarks: 125,
    eligibility: 'Class 12 with 50% aggregate in PCM.',
    officialUrl: 'https://srmist.edu.in',
    icon: 'srmjeee',
    sortOrder: 9,
  },
  {
    name: 'MET (Manipal)',
    slug: 'met',
    category: 'engineering',
    description: 'Manipal Entrance Test for Manipal Academy of Higher Education.',
    subjects: ['Physics', 'Chemistry', 'Mathematics', 'English'],
    duration: 120,
    totalMarks: 240,
    eligibility: 'Class 12 with 50% aggregate in PCM.',
    officialUrl: 'https://manipal.edu',
    icon: 'met',
    sortOrder: 10,
  },
  {
    name: 'KIITEE',
    slug: 'kiitee',
    category: 'engineering',
    description: 'Kalinga Institute of Industrial Technology Entrance Examination.',
    subjects: ['Physics', 'Chemistry', 'Mathematics'],
    duration: 180,
    totalMarks: 480,
    eligibility: 'Class 12 with 60% aggregate in PCM.',
    officialUrl: 'https://kiitee.kiit.ac.in',
    icon: 'kiitee',
    sortOrder: 11,
  },
  {
    name: 'AP EAMCET',
    slug: 'ap-eamcet',
    category: 'engineering',
    description: 'Andhra Pradesh Engineering, Agriculture and Pharmacy Common Entrance Test.',
    subjects: ['Mathematics', 'Physics', 'Chemistry'],
    duration: 180,
    totalMarks: 160,
    eligibility: 'AP domicile Class 12 passed with PCM.',
    officialUrl: 'https://cets.apsche.ap.gov.in',
    icon: 'ap-eamcet',
    sortOrder: 12,
  },
  {
    name: 'TS EAMCET',
    slug: 'ts-eamcet',
    category: 'engineering',
    description: 'Telangana State Engineering, Agriculture and Medical Common Entrance Test.',
    subjects: ['Mathematics', 'Physics', 'Chemistry'],
    duration: 180,
    totalMarks: 160,
    eligibility: 'TS domicile Class 12 passed with PCM.',
    officialUrl: 'https://eapcet.tsche.ac.in',
    icon: 'ts-eamcet',
    sortOrder: 13,
  },
  {
    name: 'GUJCET',
    slug: 'gujcet',
    category: 'engineering',
    description: 'Gujarat Common Entrance Test for state engineering colleges.',
    subjects: ['Physics', 'Chemistry', 'Mathematics'],
    duration: 180,
    totalMarks: 120,
    eligibility: 'Class 12 passed from GSEB/CBSE with PCM.',
    officialUrl: 'https://gujcet.gseb.org',
    icon: 'gujcet',
    sortOrder: 14,
  },
  {
    name: 'KEAM',
    slug: 'keam',
    category: 'engineering',
    description: 'Kerala Engineering Architecture Medical Entrance Examination.',
    subjects: ['Physics', 'Chemistry', 'Mathematics'],
    duration: 150,
    totalMarks: 300,
    eligibility: 'Class 12 passed with 45% in PCM.',
    officialUrl: 'https://cee.kerala.gov.in',
    icon: 'keam',
    sortOrder: 15,
  },

  // ─── Medical Entrance ───────────────────────────────────────────────────────────
  {
    name: 'NEET UG',
    slug: 'neet-ug',
    category: 'medical',
    description: 'National Eligibility cum Entrance Test — undergraduate medical entrance.',
    subjects: ['Physics', 'Chemistry', 'Biology (Botany)', 'Biology (Zoology)'],
    duration: 200,
    totalMarks: 720,
    eligibility: 'Class 12 passed with PCB and English.',
    officialUrl: 'https://neet.nta.nic.in',
    icon: 'neet',
    sortOrder: 16,
  },
  {
    name: 'NEET PG',
    slug: 'neet-pg',
    category: 'medical',
    description: 'National Eligibility cum Entrance Test for Postgraduate MD/MS/Diploma courses.',
    subjects: ['Pre-Clinical', 'Para-Clinical', 'Clinical Subjects'],
    duration: 210,
    totalMarks: 800,
    eligibility: 'MBBS degree with completed internship.',
    officialUrl: 'https://nbe.edu.in',
    icon: 'neet-pg',
    sortOrder: 17,
  },
  {
    name: 'INI CET',
    slug: 'ini-cet',
    category: 'medical',
    description: 'Institute of National Importance Combined Entrance Test for AIIMS, JIPMER, PGI.',
    subjects: ['Basic Medical Sciences', 'Clinical Specialities'],
    duration: 180,
    totalMarks: 200,
    eligibility: 'MBBS degree from recognized institute.',
    officialUrl: 'https://aiimsexams.ac.in',
    icon: 'ini-cet',
    sortOrder: 18,
  },
  {
    name: 'FMGE',
    slug: 'fmge',
    category: 'medical',
    description: 'Foreign Medical Graduate Examination screening test by NBE.',
    subjects: ['Pre & Para Clinical', 'Clinical Subjects'],
    duration: 300,
    totalMarks: 300,
    eligibility: 'Primary medical qualification outside India.',
    officialUrl: 'https://nbe.edu.in',
    icon: 'fmge',
    sortOrder: 19,
  },

  // ─── Government Jobs & SSC ──────────────────────────────────────────────────────
  {
    name: 'SSC CGL',
    slug: 'ssc-cgl',
    category: 'government',
    description: 'Staff Selection Commission Combined Graduate Level examination.',
    subjects: ['General Intelligence', 'English Language', 'Quantitative Aptitude', 'General Awareness'],
    duration: 60,
    totalMarks: 200,
    eligibility: 'Graduate from a recognised university.',
    officialUrl: 'https://ssc.gov.in',
    icon: 'ssc',
    sortOrder: 20,
  },
  {
    name: 'SSC CHSL',
    slug: 'ssc-chsl',
    category: 'government',
    description: 'Staff Selection Commission Combined Higher Secondary Level exam.',
    subjects: ['General Intelligence', 'English Language', 'Quantitative Aptitude', 'General Awareness'],
    duration: 60,
    totalMarks: 200,
    eligibility: 'Class 12 passed.',
    officialUrl: 'https://ssc.gov.in',
    icon: 'ssc-chsl',
    sortOrder: 21,
  },
  {
    name: 'SSC MTS',
    slug: 'ssc-mts',
    category: 'government',
    description: 'Staff Selection Commission Multi-Tasking Staff examination.',
    subjects: ['Numerical & Mathematical Ability', 'Reasoning Ability', 'General Awareness', 'English Language'],
    duration: 90,
    totalMarks: 270,
    eligibility: 'Class 10 (Matriculation) passed.',
    officialUrl: 'https://ssc.gov.in',
    icon: 'ssc-mts',
    sortOrder: 22,
  },
  {
    name: 'SSC CPO',
    slug: 'ssc-cpo',
    category: 'government',
    description: 'SSC Central Police Organisation for Sub-Inspector in Delhi Police & CAPF.',
    subjects: ['General Intelligence', 'General Knowledge', 'Quantitative Aptitude', 'English Comprehension'],
    duration: 120,
    totalMarks: 200,
    eligibility: 'Graduate degree.',
    officialUrl: 'https://ssc.gov.in',
    icon: 'ssc-cpo',
    sortOrder: 23,
  },
  {
    name: 'SSC GD Constable',
    slug: 'ssc-gd',
    category: 'government',
    description: 'SSC General Duty Constable examination for BSF, CISF, CRPF, SSB.',
    subjects: ['Reasoning', 'General Knowledge', 'Elementary Mathematics', 'English/Hindi'],
    duration: 60,
    totalMarks: 160,
    eligibility: 'Class 10 passed.',
    officialUrl: 'https://ssc.gov.in',
    icon: 'ssc-gd',
    sortOrder: 24,
  },
  {
    name: 'SSC JE',
    slug: 'ssc-je',
    category: 'government',
    description: 'SSC Junior Engineer for Civil, Mechanical, and Electrical streams.',
    subjects: ['General Intelligence', 'General Awareness', 'Engineering Domain (Civil/ME/EE)'],
    duration: 120,
    totalMarks: 200,
    eligibility: 'Degree or Diploma in Engineering.',
    officialUrl: 'https://ssc.gov.in',
    icon: 'ssc-je',
    sortOrder: 25,
  },

  // ─── Railways (RRB) ─────────────────────────────────────────────────────────────
  {
    name: 'RRB NTPC',
    slug: 'rrb-ntpc',
    category: 'government',
    description: 'Railway Recruitment Board Non-Technical Popular Categories exam.',
    subjects: ['General Awareness', 'Mathematics', 'General Intelligence & Reasoning'],
    duration: 90,
    totalMarks: 100,
    eligibility: 'Class 12 / Graduate depending on post.',
    officialUrl: 'https://indianrailways.gov.in',
    icon: 'rrb-ntpc',
    sortOrder: 26,
  },
  {
    name: 'RRB JE',
    slug: 'rrb-je',
    category: 'government',
    description: 'Railway Recruitment Board Junior Engineer examination.',
    subjects: ['Mathematics', 'General Intelligence', 'General Awareness', 'General Science', 'Technical Abilities'],
    duration: 90,
    totalMarks: 100,
    eligibility: 'Degree/Diploma in Engineering.',
    officialUrl: 'https://indianrailways.gov.in',
    icon: 'rrb-je',
    sortOrder: 27,
  },
  {
    name: 'RRB ALP',
    slug: 'rrb-alp',
    category: 'government',
    description: 'Railway Recruitment Board Assistant Loco Pilot & Technician exam.',
    subjects: ['Mathematics', 'General Intelligence', 'General Science', 'Basic Science & Engineering'],
    duration: 60,
    totalMarks: 75,
    eligibility: 'Matriculation + ITI / Diploma in Engineering.',
    officialUrl: 'https://indianrailways.gov.in',
    icon: 'rrb-alp',
    sortOrder: 28,
  },

  // ─── Banking & Insurance ────────────────────────────────────────────────────────
  {
    name: 'IBPS PO',
    slug: 'ibps-po',
    category: 'banking',
    description: 'Institute of Banking Personnel Selection Probationary Officer exam.',
    subjects: ['English Language', 'Quantitative Aptitude', 'Reasoning Ability', 'General Awareness', 'Computer Aptitude'],
    duration: 60,
    totalMarks: 200,
    eligibility: 'Graduate from recognized university.',
    officialUrl: 'https://ibps.in',
    icon: 'ibps',
    sortOrder: 29,
  },
  {
    name: 'IBPS Clerk',
    slug: 'ibps-clerk',
    category: 'banking',
    description: 'Institute of Banking Personnel Selection Clerical Cadre exam.',
    subjects: ['English Language', 'Numerical Ability', 'Reasoning Ability', 'General Financial Awareness'],
    duration: 60,
    totalMarks: 100,
    eligibility: 'Graduate from recognized university.',
    officialUrl: 'https://ibps.in',
    icon: 'ibps-clerk',
    sortOrder: 30,
  },
  {
    name: 'SBI PO',
    slug: 'sbi-po',
    category: 'banking',
    description: 'State Bank of India Probationary Officer recruitment exam.',
    subjects: ['English Language', 'Quantitative Aptitude', 'Reasoning Ability', 'General Awareness', 'Data Analysis'],
    duration: 60,
    totalMarks: 200,
    eligibility: 'Graduate from recognized university.',
    officialUrl: 'https://sbi.co.in/careers',
    icon: 'sbi',
    sortOrder: 31,
  },
  {
    name: 'SBI Clerk',
    slug: 'sbi-clerk',
    category: 'banking',
    description: 'State Bank of India Junior Associate (Customer Support & Sales) exam.',
    subjects: ['English Language', 'Numerical Ability', 'Reasoning Ability', 'General Awareness'],
    duration: 60,
    totalMarks: 100,
    eligibility: 'Graduate from recognized university.',
    officialUrl: 'https://sbi.co.in/careers',
    icon: 'sbi-clerk',
    sortOrder: 32,
  },
  {
    name: 'RBI Grade B',
    slug: 'rbi-grade-b',
    category: 'banking',
    description: 'Reserve Bank of India Officers in Grade B examination.',
    subjects: ['General Awareness', 'English Language', 'Quantitative Aptitude', 'Reasoning', 'Economic & Social Issues'],
    duration: 120,
    totalMarks: 200,
    eligibility: 'Graduate with minimum 60% marks.',
    officialUrl: 'https://rbi.org.in',
    icon: 'rbi',
    sortOrder: 33,
  },

  // ─── Civil Services & Defence ───────────────────────────────────────────────────
  {
    name: 'UPSC CSE',
    slug: 'upsc-cse',
    category: 'government',
    description: 'Union Public Service Commission Civil Services Examination (IAS/IPS/IFS).',
    subjects: ['General Studies', 'CSAT', 'Optional Subject', 'Essay', 'Ethics'],
    duration: 120,
    totalMarks: 2025,
    eligibility: 'Graduate from a recognized university.',
    officialUrl: 'https://upsc.gov.in',
    icon: 'upsc',
    sortOrder: 34,
  },
  {
    name: 'UPSC NDA',
    slug: 'upsc-nda',
    category: 'government',
    description: 'National Defence Academy & Naval Academy examination.',
    subjects: ['Mathematics', 'General Ability Test (GAT)'],
    duration: 300,
    totalMarks: 900,
    eligibility: 'Class 12 passed (Physics & Maths for Air Force/Navy).',
    officialUrl: 'https://upsc.gov.in',
    icon: 'nda',
    sortOrder: 35,
  },
  {
    name: 'UPSC CDS',
    slug: 'upsc-cds',
    category: 'government',
    description: 'Combined Defence Services examination for IMA, INA, AFA, OTA.',
    subjects: ['English', 'General Knowledge', 'Elementary Mathematics'],
    duration: 120,
    totalMarks: 300,
    eligibility: 'Graduate degree in relevant discipline.',
    officialUrl: 'https://upsc.gov.in',
    icon: 'cds',
    sortOrder: 36,
  },
  {
    name: 'AFCAT',
    slug: 'afcat',
    category: 'government',
    description: 'Air Force Common Admission Test for Flying & Ground Duty branches.',
    subjects: ['Verbal Ability', 'Numerical Ability', 'Reasoning & Military Aptitude', 'General Awareness'],
    duration: 120,
    totalMarks: 300,
    eligibility: 'Graduate with 60% aggregate in Maths/Physics at 10+2.',
    officialUrl: 'https://afcat.cdac.in',
    icon: 'afcat',
    sortOrder: 37,
  },
  {
    name: 'UPPSC PCS',
    slug: 'uppsc',
    category: 'government',
    description: 'Uttar Pradesh Combined State / Upper Subordinate Services Exam.',
    subjects: ['General Studies I', 'General Studies II (CSAT)', 'Hindi', 'Essay'],
    duration: 120,
    totalMarks: 1500,
    eligibility: 'Graduate degree.',
    officialUrl: 'https://uppsc.up.nic.in',
    icon: 'uppsc',
    sortOrder: 38,
  },
  {
    name: 'BPSC CCE',
    slug: 'bpsc',
    category: 'government',
    description: 'Bihar Public Service Commission Combined Competitive Examination.',
    subjects: ['General Studies', 'General Hindi', 'Optional Subject'],
    duration: 120,
    totalMarks: 900,
    eligibility: 'Graduate degree.',
    officialUrl: 'https://bpsc.bih.nic.in',
    icon: 'bpsc',
    sortOrder: 39,
  },

  // ─── Management & B-Schools ─────────────────────────────────────────────────────
  {
    name: 'CAT',
    slug: 'cat',
    category: 'management',
    description: 'Common Admission Test for IIMs and premier management institutes.',
    subjects: ['VARC (Verbal & Reading)', 'DILR (Data & Reasoning)', 'QA (Quantitative Ability)'],
    duration: 120,
    totalMarks: 198,
    eligibility: 'Bachelor degree with minimum 50% marks.',
    officialUrl: 'https://iimcat.ac.in',
    icon: 'cat',
    sortOrder: 40,
  },
  {
    name: 'XAT',
    slug: 'xat',
    category: 'management',
    description: 'Xavier Aptitude Test conducted by XLRI Jamshedpur.',
    subjects: ['Verbal & Logical Ability', 'Decision Making', 'Quantitative Ability & Data Tech', 'General Knowledge'],
    duration: 210,
    totalMarks: 100,
    eligibility: 'Bachelor degree in any discipline.',
    officialUrl: 'https://xatonline.in',
    icon: 'xat',
    sortOrder: 41,
  },
  {
    name: 'NMAT',
    slug: 'nmat',
    category: 'management',
    description: 'NMAT by GMAC for NMIMS and top global business schools.',
    subjects: ['Language Skills', 'Quantitative Skills', 'Logical Reasoning'],
    duration: 120,
    totalMarks: 360,
    eligibility: 'Bachelor degree with 50% marks.',
    officialUrl: 'https://nmat.org',
    icon: 'nmat',
    sortOrder: 42,
  },
  {
    name: 'SNAP',
    slug: 'snap',
    category: 'management',
    description: 'Symbiosis National Aptitude Test for Symbiosis International University.',
    subjects: ['General English', 'Analytical & Logical Reasoning', 'Quantitative & Data Interpretation'],
    duration: 60,
    totalMarks: 60,
    eligibility: 'Graduate with 50% marks.',
    officialUrl: 'https://snaptest.org',
    icon: 'snap',
    sortOrder: 43,
  },

  // ─── Law Entrance ───────────────────────────────────────────────────────────────
  {
    name: 'CLAT UG',
    slug: 'clat-ug',
    category: 'law',
    description: 'Common Law Admission Test for 22+ National Law Universities (NLUs).',
    subjects: ['English Language', 'Current Affairs & GK', 'Legal Reasoning', 'Logical Reasoning', 'Quantitative Techniques'],
    duration: 120,
    totalMarks: 120,
    eligibility: 'Class 12 passed with 45% marks.',
    officialUrl: 'https://consortiumofnlus.ac.in',
    icon: 'clat',
    sortOrder: 44,
  },
  {
    name: 'AILET',
    slug: 'ailet',
    category: 'law',
    description: 'All India Law Entrance Test for National Law University (NLU Delhi).',
    subjects: ['English Language', 'Current Affairs & GK', 'Logical Reasoning'],
    duration: 120,
    totalMarks: 150,
    eligibility: 'Class 12 passed with 45% marks.',
    officialUrl: 'https://nationallawuniversitydelhi.in',
    icon: 'ailet',
    sortOrder: 45,
  },

  // ─── Graduate & Research (GATE / NET) ────────────────────────────────────────────
  {
    name: 'GATE Computer Science',
    slug: 'gate-cs',
    category: 'graduate',
    description: 'Graduate Aptitude Test in Engineering — CS & Information Technology.',
    subjects: ['General Aptitude', 'Engineering Mathematics', 'Computer Science Core'],
    duration: 180,
    totalMarks: 100,
    eligibility: 'B.E./B.Tech/M.Sc in relevant field.',
    officialUrl: 'https://gate.iisc.ac.in',
    icon: 'gate',
    sortOrder: 46,
  },
  {
    name: 'GATE Electronics (EC)',
    slug: 'gate-ec',
    category: 'graduate',
    description: 'Graduate Aptitude Test in Engineering — Electronics & Communication.',
    subjects: ['General Aptitude', 'Engineering Mathematics', 'Electronics & Signals'],
    duration: 180,
    totalMarks: 100,
    eligibility: 'B.E./B.Tech in EC/EE.',
    officialUrl: 'https://gate.iisc.ac.in',
    icon: 'gate-ec',
    sortOrder: 47,
  },
  {
    name: 'UGC NET',
    slug: 'ugc-net',
    category: 'graduate',
    description: 'University Grants Commission National Eligibility Test for Assistant Professor / JRF.',
    subjects: ['Teaching & Research Aptitude', 'Subject Core'],
    duration: 180,
    totalMarks: 300,
    eligibility: 'Master degree with 55% aggregate.',
    officialUrl: 'https://ugcnet.nta.ac.in',
    icon: 'ugc-net',
    sortOrder: 48,
  },

  // ─── School Boards ──────────────────────────────────────────────────────────────
  {
    name: 'CBSE Class 10',
    slug: 'cbse-class-10',
    category: 'boards',
    description: 'Central Board of Secondary Education Class 10 board examinations.',
    subjects: ['Mathematics', 'Science', 'Social Science', 'English', 'Hindi'],
    duration: 180,
    totalMarks: 500,
    eligibility: 'Students enrolled in CBSE-affiliated schools.',
    officialUrl: 'https://cbse.gov.in',
    icon: 'cbse',
    sortOrder: 49,
  },
  {
    name: 'CBSE Class 12',
    slug: 'cbse-class-12',
    category: 'boards',
    description: 'Central Board of Secondary Education Class 12 board examinations.',
    subjects: ['Physics', 'Chemistry', 'Mathematics', 'English', 'Computer Science'],
    duration: 180,
    totalMarks: 500,
    eligibility: 'Students enrolled in CBSE-affiliated schools.',
    officialUrl: 'https://cbse.gov.in',
    icon: 'cbse',
    sortOrder: 50,
  },
  {
    name: 'ICSE Class 10',
    slug: 'icse-class-10',
    category: 'boards',
    description: 'Indian Certificate of Secondary Education Class 10 board examinations.',
    subjects: ['Mathematics', 'Science', 'History & Civics', 'Geography', 'English'],
    duration: 180,
    totalMarks: 500,
    eligibility: 'Students enrolled in ICSE-affiliated schools.',
    officialUrl: 'https://cisce.org',
    icon: 'icse',
    sortOrder: 51,
  },
  {
    name: 'ISC Class 12',
    slug: 'isc-class-12',
    category: 'boards',
    description: 'Indian School Certificate Class 12 board examinations.',
    subjects: ['Physics', 'Chemistry', 'Mathematics', 'English', 'Computer Science'],
    duration: 180,
    totalMarks: 500,
    eligibility: 'Students enrolled in ISC-affiliated schools.',
    officialUrl: 'https://cisce.org',
    icon: 'isc',
    sortOrder: 52,
  },

  // ─── Overseas & Aptitude ────────────────────────────────────────────────────────
  {
    name: 'SAT',
    slug: 'sat',
    category: 'overseas',
    description: 'Scholastic Assessment Test for undergraduate university admissions globally.',
    subjects: ['Reading & Writing', 'Math'],
    duration: 134,
    totalMarks: 1600,
    eligibility: 'High school students.',
    officialUrl: 'https://satsuite.collegeboard.org',
    icon: 'sat',
    sortOrder: 53,
  },
  {
    name: 'GRE General',
    slug: 'gre',
    category: 'overseas',
    description: 'Graduate Record Examinations for master & doctoral programs worldwide.',
    subjects: ['Analytical Writing', 'Verbal Reasoning', 'Quantitative Reasoning'],
    duration: 115,
    totalMarks: 340,
    eligibility: 'Bachelor degree students.',
    officialUrl: 'https://ets.org/gre',
    icon: 'gre',
    sortOrder: 54,
  },
];

module.exports = EXAM_SEEDS;
