/**
 * StudyOS - Exam Seed Data
 *
 * Predefined exams that are seeded into the database on first run.
 * Each entry matches the Exam model schema.
 */

const EXAM_SEEDS = [
  {
    name: 'JEE Main',
    slug: 'jee-main',
    category: 'engineering',
    description: 'Joint Entrance Examination Main — national-level entrance for NITs, IIITs, and CFTIs.',
    subjects: ['Physics', 'Chemistry', 'Mathematics'],
    duration: 180,
    totalMarks: 300,
    eligibility: 'Class 12 passed or appearing with Physics and Mathematics as compulsory subjects.',
    officialUrl: 'https://jeemain.nta.nic.in',
    icon: 'jee',
    sortOrder: 1,
  },
  {
    name: 'JEE Advanced',
    slug: 'jee-advanced',
    category: 'engineering',
    description: 'Joint Entrance Examination Advanced — entrance for IITs. Requires JEE Main qualification.',
    subjects: ['Physics', 'Chemistry', 'Mathematics'],
    duration: 180,
    totalMarks: 360,
    eligibility: 'Must qualify JEE Main and be in top 2,50,000 candidates.',
    officialUrl: 'https://jeeadv.ac.in',
    icon: 'jee-adv',
    sortOrder: 2,
  },
  {
    name: 'NEET UG',
    slug: 'neet-ug',
    category: 'medical',
    description: 'National Eligibility cum Entrance Test — entrance for MBBS, BDS, and AYUSH courses.',
    subjects: ['Physics', 'Chemistry', 'Biology (Botany)', 'Biology (Zoology)'],
    duration: 200,
    totalMarks: 720,
    eligibility: 'Class 12 passed or appearing with Physics, Chemistry, and Biology.',
    officialUrl: 'https://neet.nta.nic.in',
    icon: 'neet',
    sortOrder: 3,
  },
  {
    name: 'UPSC CSE',
    slug: 'upsc-cse',
    category: 'government',
    description: 'Union Public Service Commission Civil Services Examination — India\'s premier government service exam.',
    subjects: ['General Studies', 'CSAT', 'Optional Subject', 'Essay', 'Ethics'],
    duration: 120,
    totalMarks: 2025,
    eligibility: 'Graduate from a recognised university. Age 21–32 (with relaxations).',
    officialUrl: 'https://upsc.gov.in',
    icon: 'upsc',
    sortOrder: 4,
  },
  {
    name: 'SSC CGL',
    slug: 'ssc-cgl',
    category: 'government',
    description: 'Staff Selection Commission Combined Graduate Level — recruitment for Group B and C posts.',
    subjects: ['General Intelligence', 'English Language', 'Quantitative Aptitude', 'General Awareness'],
    duration: 60,
    totalMarks: 200,
    eligibility: 'Graduate from a recognised university. Age 18–32.',
    officialUrl: 'https://ssc.nic.in',
    icon: 'ssc',
    sortOrder: 5,
  },
  {
    name: 'SSC CHSL',
    slug: 'ssc-chsl',
    category: 'government',
    description: 'Staff Selection Commission Combined Higher Secondary Level — recruitment for LDC, DEO, and PA posts.',
    subjects: ['General Intelligence', 'English Language', 'Quantitative Aptitude', 'General Awareness'],
    duration: 60,
    totalMarks: 200,
    eligibility: 'Class 12 passed from a recognised board. Age 18–27.',
    officialUrl: 'https://ssc.nic.in',
    icon: 'ssc-chsl',
    sortOrder: 6,
  },
  {
    name: 'IBPS PO',
    slug: 'ibps-po',
    category: 'banking',
    description: 'Institute of Banking Personnel Selection Probationary Officer — entrance for public sector bank PO positions.',
    subjects: ['English Language', 'Quantitative Aptitude', 'Reasoning Ability', 'General Awareness', 'Computer Aptitude'],
    duration: 60,
    totalMarks: 200,
    eligibility: 'Graduate from a recognised university. Age 20–30.',
    officialUrl: 'https://ibps.in',
    icon: 'ibps',
    sortOrder: 7,
  },
  {
    name: 'SBI PO',
    slug: 'sbi-po',
    category: 'banking',
    description: 'State Bank of India Probationary Officer — direct recruitment for SBI officer cadre.',
    subjects: ['English Language', 'Quantitative Aptitude', 'Reasoning Ability', 'General Awareness', 'Computer Aptitude'],
    duration: 60,
    totalMarks: 200,
    eligibility: 'Graduate from a recognised university. Age 21–30.',
    officialUrl: 'https://sbi.co.in/careers',
    icon: 'sbi',
    sortOrder: 8,
  },
  {
    name: 'CBSE Class 10',
    slug: 'cbse-class-10',
    category: 'boards',
    description: 'Central Board of Secondary Education Class 10 board examinations.',
    subjects: ['Mathematics', 'Science', 'Social Science', 'English', 'Hindi'],
    duration: 180,
    totalMarks: 500,
    eligibility: 'Students enrolled in CBSE-affiliated schools.',
    officialUrl: 'https://cbse.gov.in',
    icon: 'cbse',
    sortOrder: 9,
  },
  {
    name: 'CBSE Class 12',
    slug: 'cbse-class-12',
    category: 'boards',
    description: 'Central Board of Secondary Education Class 12 board examinations.',
    subjects: ['Physics', 'Chemistry', 'Mathematics', 'English', 'Computer Science'],
    duration: 180,
    totalMarks: 500,
    eligibility: 'Students enrolled in CBSE-affiliated schools.',
    officialUrl: 'https://cbse.gov.in',
    icon: 'cbse',
    sortOrder: 10,
  },
  {
    name: 'ICSE Class 10',
    slug: 'icse-class-10',
    category: 'boards',
    description: 'Indian Certificate of Secondary Education Class 10 board examinations.',
    subjects: ['Mathematics', 'Science', 'History & Civics', 'Geography', 'English'],
    duration: 180,
    totalMarks: 500,
    eligibility: 'Students enrolled in ICSE-affiliated schools.',
    officialUrl: 'https://cisce.org',
    icon: 'icse',
    sortOrder: 11,
  },
  {
    name: 'ISC Class 12',
    slug: 'isc-class-12',
    category: 'boards',
    description: 'Indian School Certificate Class 12 board examinations.',
    subjects: ['Physics', 'Chemistry', 'Mathematics', 'English', 'Computer Science'],
    duration: 180,
    totalMarks: 500,
    eligibility: 'Students enrolled in ISC-affiliated schools.',
    officialUrl: 'https://cisce.org',
    icon: 'isc',
    sortOrder: 12,
  },
];

module.exports = EXAM_SEEDS;
